#ansible-playbook test-playbook-galaxy.yml --extra-vars "ansible_become_pass=sudo_pass"
#To run without installing software dependencies
#ansible-playbook test-playbook-galaxy.yml --extra-vars "ansible_become_pass=sudo_pass" --skip-tags "software"
- hosts: localhost

  vars_files:
    - ../../../../group_vars/all.yml

  tasks:
    - name: Tempalte mainyml.j2
      template:
        src: meta/mainyml.j2
        dest: meta/main.yml

    - name: Tempalte mainyml.j2
      template:
        src: requirementsyml.j2
        dest: requirements.yml

- hosts: localhost

  vars_files: ../../../../group_vars/all.yml

  tasks:
    - name: Including role to test
      include_role:
        name: '../software_terraform'
