- name: Installing binnaries
  become: true
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
    dest: /usr/local/bin/
#  with_items: "{{ software_packages }}"



- name: Extract binnaries
  become: true
  unarchive:
    src: /usr/local/bin/terraform_0.11.14_linux_amd64.zip
    dest: /usr/local/bin/
#    mode:

#byxussof millorarlo amb bones vars
