#byxussof Make it available for mac and other linux distros
- name: Installing binnaries
  become: true
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ software_version }}/terraform_{{ software_version }}_linux_amd64.zip"
    dest: /usr/local/bin/
#  with_items: "{{ software_packages }}"



- name: Extract binnaries
  become: true
  unarchive:
    src: "/usr/local/bin/terraform_{{ software_version }}_linux_amd64.zip"
    dest: /usr/local/bin/
#    mode:

#byxussof millorarlo amb bones vars
